import 'package:green_tech_test/Model/picture.dart';

List<Picture> pictureList = [
  Picture(
    id: "1",
    title: "Flaring Bowl with Inner Rim Depicting Undulating Serpents",
    type: "Vessel",
    artist: "Kate S. Buckingham Endowment",
    dateDisplayed: "100 BCE–500 CE",
    country: "Peruvian North Coast",
  ),
  Picture(
    id: "2",
    title: "God Shiva Seated in Loving Embrace with Goddess Uma on the Bull Nandi",
    type: "Sculpture",
    artist: "Kate S. Buckingham Fund",
    dateDisplayed: "9th century",
    country: "Madhya Pradesh",
  ),
  Picture(
    id: "3",
    title: "God Shiva as the Supreme Teacher (Dakshinamurti)",
    type: "Sculpture",
    artist: "Kate S. Buckingham Fund",
    dateDisplayed: "10th century",
    country: "Kodumbalur",
  ),
  Picture(
    id: "4",
    title: "Buddhist figures in Paradise",
    type: "Painting",
    artist: "Gift of Mr. and Mrs. Eugene W. Kettering",
    dateDisplayed: "Bangkok period, 19th century",
    country: "Thailand",
  ),
  Picture(
    id: "5",
    title: "The Fire Next Time, from Human_3.0 Reading List",
    type: "Drawing and Watercolor",
    artist: "Gift of Helen and Sam Zell",
    dateDisplayed: "2015",
    country: "United States",
  ),
  Picture(
    id: "6",
    title: "Wild Seed, from Human_3.0 Reading List",
    type: "Drawing and Watercolor",
    artist: "Kate S. Buckingham Endowment",
    dateDisplayed: "2015",
    country: "United States",
  ),
  Picture(
    id: "7",
    title: "Ceremonial Grinding Table (Metate)",
    type: "Sculpture",
    artist: "Gift of Mrs. Everett McNear in memory of Everett McNear",
    dateDisplayed: "1–500 CE",
    country: "Nicoya",
  ),
  Picture(
    id: "8",
    title: "Temple Strut with Bodhisattva Standing on a Lion",
    type: "Architectural fragment",
    artist: "James W. and Marilynn Alsdorf Collection",
    dateDisplayed: "18th century",
    country: "Nepal",
  ),
  Picture(
    id: "9",
    title: "Head of a Woman with a Chignon (Fernande)",
    type: "Drawing and Watercolor",
    artist: "Partial and promised gift of Susan Manilow in memory of Lew Manilow",
    dateDisplayed: "summer 1906",
    country: "Spain",
  ),
  Picture(
    id: "10",
    title: "Seated Female Nude",
    type: "Drawing and Watercolor",
    artist: "Mr. and Mrs. Carter H. Harrison Collection",
    dateDisplayed: "c. 1925",
    country: "France",
  ),
  Picture(
    id: "11",
    title: "La Java",
    type: "Painting",
    artist: "Gift of Mr. and Mrs. Carter H. Harrison",
    dateDisplayed: "1925",
    country: "France",
  ),
  Picture(
    id: "12",
    title: "Plants, Porcelain Bowl, and Glass Goblet",
    type: "Print",
    artist: "Clarence Buckingham Collection",
    dateDisplayed: "c. 1789",
    country: "Japan",
  ),
];
